### ISSUE TITLE
Error: cannot open 'glib'

### ISSUE THREAD

**Issue by shawnye** [SSPkrolik/nim-native-dialogs#4]
build on linux mint 17.3 cinnamon.

<pre>
/home/shawnye/.nimble/pkgs/native_dialogs-0.1.0/native_dialogs.nim(23, 10) Error: cannot open 'glib'
Traceback (most recent call last)
nimble.nim(962)          nimble
nimble.nim(907)          doAction
nimble.nim(563)          build
nimble.nim(321)          buildFromDir
Error: unhandled exception: Build failed for package: dialogtest [BuildFailed]
</pre>

It seems that it fail to `import glib`

I have installed `libglib2.0-0:i386`, `libglib2.0-dev` , but it is of no veil.

Any suggestion? Thank you!

**Comment by SSPkrolik** [comment]
@shawnye Could you please check if `glib` is present in your package dir? (/shawnye/.nimble/pkgs//glib-2.42/)
